=== dkent600/douglaskent/src/static/schema.json
{
  "$id": "https://douglaskent.com/schemas/resume",
  "$schema": "https://json-schema.org/draft-04/schema#",
  "title": "Resume Schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string"
    },
    "basics": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "name": {
          "type": "string"
        },
        "label": {
          "type": "string",
          "description": "e.g. Web Developer"
        },
        "image": {
          "type": "string",
          "description": "URL (as per RFC 3986) to a image in JPEG or PNG format"
        },
        "email": {
          "type": "string",
          "description": "e.g. thomas@gmail.com",
          "format": "email"
        },
        "phone": {
          "type": "string",
          "description": "Phone numbers are stored as strings so use any format you like, e.g. 712-117-2923"
        },
        "url": {
          "type": "string",
          "description": "URL (as per RFC 3986) to your website, e.g. personal homepage",
          "format": "uri"
        },
        "summary1": {
          "type": "string",
          "description": "Write a biography about yourself"
        },
        "summary2": {
          "type": "string",
          "description": "Write a biography about yourself"
        },
        "summary3": {
          "type": "string",
          "description": "Write a biography about yourself"
        },
        "location": {
          "type": "object",
          "additionalProperties": true,
          "properties": {
            "address": {
              "type": "string",
              "description": "To add multiple address lines, use \n. For example, 1234 Gl�cklichkeit Stra�e\nHinterhaus 5. Etage li."
            },
            "postalCode": {
              "type": "string"
            },
            "city": {
              "type": "string"
            },
            "countryCode": {
              "type": "string",
              "description": "code as per ISO-3166-1 ALPHA-2, e.g. US, AU, IN"
            },
            "region": {
              "type": "string",
              "description": "The general region where you live. Can be a US state, or a province, for instance."
            }
          }
        },
        "profiles": {
          "type": "array",
          "description": "Specify any number of social networks that you participate in",
          "additionalItems": false,
          "items": {
            "type": "object",
            "additionalProperties": true,
            "properties": {
              "network": {
                "type": "string",
                "description": "e.g. Facebook or Twitter"
              },
              "username": {
                "type": "string",
                "description": "e.g. neutralthoughts"
              },
              "url": {
                "type": "string",
                "description": "e.g. https://twitter.example.com/neutralthoughts"
              }
            }
          }
        }
      }
    },
    "work": {
      "type": "array",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "name": {
            "type": "string",
            "description": "e.g. Facebook"
          },
          "location": {
            "type": "string",
            "description": "e.g. Menlo Park, CA"
          },
          "description": {
            "type": "string",
            "description": "e.g. Social Media Company"
          },
          "position": {
            "type": "string",
            "description": "e.g. Software Engineer"
          },
          "url": {
            "type": "string",
            "description": "e.g. https://facebook.example.com",
            "format": "uri"
          },
          "startDate": {
            "type": "string",
            "description": "resume.json uses the ISO 8601 date standard e.g. 2014-06-29",
            "format": "date"
          },
          "endDate": {
            "type": "string",
            "description": "e.g. 2012-06-29",
            "format": "date"
          },
          "summary": {
            "type": "string",
            "description": "Give an overview of your responsibilities at the company"
          },
          "highlights": {
            "type": "array",
            "description": "Specify multiple accomplishments",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. Increased profits by 20% from 2011-2012 through viral advertising"
            }
          }
        }
      }
    },
    "volunteer": {
      "type": "array",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "organization": {
            "type": "string",
            "description": "e.g. Facebook"
          },
          "position": {
            "type": "string",
            "description": "e.g. Software Engineer"
          },
          "url": {
            "type": "string",
            "description": "e.g. https://facebook.example.com",
            "format": "uri"
          },
          "startDate": {
            "type": "string",
            "description": "resume.json uses the ISO 8601 date standard e.g. 2014-06-29",
            "format": "date"
          },
          "endDate": {
            "type": "string",
            "description": "e.g. 2012-06-29",
            "format": "date"
          },
          "summary": {
            "type": "string",
            "description": "Give an overview of your responsibilities at the company"
          },
          "highlights": {
            "type": "array",
            "description": "Specify accomplishments and achievements",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. Increased profits by 20% from 2011-2012 through viral advertising"
            }
          }
        }
      }
    },
    "education": {
      "type": "array",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "institution": {
            "type": "string",
            "description": "e.g. Massachusetts Institute of Technology"
          },
          "area": {
            "type": "string",
            "description": "e.g. Arts"
          },
          "studyType": {
            "type": "string",
            "description": "e.g. Bachelor"
          },
          "startDate": {
            "type": "string",
            "description": "e.g. 2014-06-29",
            "format": "date"
          },
          "endDate": {
            "type": "string",
            "description": "e.g. 2012-06-29",
            "format": "date"
          },
          "gpa": {
            "type": "string",
            "description": "grade point average, e.g. 3.67/4.0"
          },
          "courses": {
            "type": "array",
            "description": "List notable courses/subjects",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. H1302 - Introduction to American history"
            }
          }
        }
      }
    },
    "awards": {
      "type": "array",
      "description": "Specify any awards you have received throughout your professional career",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "title": {
            "type": "string",
            "description": "e.g. One of the 100 greatest minds of the century"
          },
          "date": {
            "type": "string",
            "description": "e.g. 1989-06-12",
            "format": "date"
          },
          "awarder": {
            "type": "string",
            "description": "e.g. Time Magazine"
          },
          "summary": {
            "type": "string",
            "description": "e.g. Received for my work with Quantum Physics"
          }
        }
      }
    },
    "publications": {
      "type": "array",
      "description": "Specify your publications through your career",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "name": {
            "type": "string",
            "description": "e.g. The World Wide Web"
          },
          "publisher": {
            "type": "string",
            "description": "e.g. IEEE, Computer Magazine"
          },
          "releaseDate": {
            "type": "string",
            "description": "e.g. 1990-08-01"
          },
          "url": {
            "type": "string",
            "description": "e.g. https://www.computer.org.example.com/csdl/mags/co/1996/10/rx069-abs.html"
          },
          "summary": {
            "type": "string",
            "description": "Short summary of publication. e.g. Discussion of the World Wide Web, HTTP, HTML."
          }
        }
      }
    },
    "skills": {
      "type": "array",
      "description": "List out your professional skill-set",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "name": {
            "type": "string",
            "description": "e.g. Web Development"
          },
          "level": {
            "type": "string",
            "description": "e.g. Master"
          },
          "categories": {
            "type": "array",
            "description": "List categories pertaining to this skill",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. HTML"
            }
          }
        }
      }
    },
    "languages": {
      "type": "array",
      "description": "List any other languages you speak",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "language": {
            "type": "string",
            "description": "e.g. English, Spanish"
          },
          "fluency": {
            "type": "string",
            "description": "e.g. Fluent, Beginner"
          }
        }
      }
    },
    "interests": {
      "type": "array",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "name": {
            "type": "string",
            "description": "e.g. Philosophy"
          },
          "skills": {
            "type": "array",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. Friedrich Nietzsche"
            }
          }
        }
      }
    },
    "references": {
      "type": "array",
      "description": "List references you have received",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "name": {
            "type": "string",
            "description": "e.g. Timothy Cook"
          },
          "reference": {
            "type": "string",
            "description": "e.g. Joe blogs was a great employee, who turned up to work at least once a week. He exceeded my expectations when it came to doing nothing."
          }
        }
      }
    },
    "projects": {
      "type": "array",
      "description": "Specify career projects",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "name": {
            "type": "string",
            "description": "e.g. The World Wide Web"
          },
          "description": {
            "type": "string",
            "description": "Short summary of project. e.g. Collated works of 2017."
          },
          "highlights": {
            "type": "array",
            "description": "Specify multiple features",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. Directs you close but not quite there"
            }
          },
          "skills": {
            "type": "array",
            "description": "Specify special elements involved",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. AngularJS"
            }
          },
          "startDate": {
            "type": "string",
            "description": "resume.json uses the ISO 8601 date standard e.g. 2014-06-29",
            "format": "date"
          },
          "endDate": {
            "type": "string",
            "description": "e.g. 2012-06-29",
            "format": "date"
          },
          "url": {
            "type": "string",
            "format": "uri",
            "description": "e.g. https://www.computer.org/csdl/mags/co/1996/10/rx069-abs.html"
          },
          "roles": {
            "type": "array",
            "description": "Specify your role on this project or in company",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. Team Lead, Speaker, Writer"
            }
          },
          "entity": {
            "type": "string",
            "description": "Specify the relevant company/entity affiliations e.g. 'greenpeace', 'corporationXYZ'"
          },
          "type": {
            "type": "string",
            "description": " e.g. 'volunteering', 'presentation', 'talk', 'application', 'conference'"
          }
        }
      }
    },
    "meta": {
      "type": "object",
      "description": "The schema version and any other tooling configuration lives here",
      "additionalProperties": true,
      "properties": {
        "canonical": {
          "type": "string",
          "description": "URL (as per RFC 3986) to latest version of this document"
        },
        "version": {
          "type": "string",
          "description": "A version field which follows semver - e.g. v1.0.0"
        },
        "lastModified": {
          "type": "string",
          "description": "Using ISO 8601 with YYYY-MM-DDThh:mm:ss"
        }
      }
    },
    "skillCategories": {
      "type": "array",
      "items": {
        "type": "string",
        "uniqueItems": true
      }
    },
    "citizenship": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "country": {
            "type": "string"
          },
          "status": {
            "type": "string"
          }
        }
      }
    },
    "accomplishments": {
      "type": "array",
      "items": {
        "type": "string",
        "uniqueItems": true
      }
    },
    "qualities": {
      "type": "array",
      "items": {
        "type": "string",
        "uniqueItems": true
      }
    }
  }
}

=== dkent600/douglaskent/src/static/resume.json
{
  "$schema": "./schema-resume.json",
  "basics": {
    "name": "Douglas Kent",
    "label": "Fullstack Web3/Web Application Developer",
    "picture": "",
    "email": "resume@douglaskent.com",
    "resumeFeedbackEmail": "resume-feedback@douglaskent.com",
    "phone": "+1 (512) 402-8735 (US)",
    "phone2": "+506 8591-5302 (CR)",
    "website": "https://www.douglaskent.com",
    "summary1": "I am an <b>experienced software engineer</b> and project lead with <b>34+ years</b> of repeated success leading teams and developing sophisticated <b>Web, Web3 (blockchain) and desktop</b> applications.",
    "summary2": "As a coder, team lead or both, I have worn multiple hats in important roles in many types of situations from Microsoft to garage startups.",
    "summary3": "Please see my complete resume at: <a href='https://www.douglaskent.com' target='_blank' rel='noopener noreferrer'>https://www.douglaskent.com</a>.",
    "summary4": "I was born in the U.S. but am now based in Costa Rica. I am well accustomed to traveling and interacting with teams in such locations as in Europe, Canada, Israel, the U.S., India, Australia and others.",
    "summary5": "I've worked with the likes of Microsoft, garage startups such as ConnectSoft, to Curve Labs where I led the development of a Refi dApp front end designed to emerge a regenerative, decentralized economic system for the sovereign island nation of Curaçao.",
    "summary6": "I hope we can develop a mutually-beneficial and antifragile relationship together. Thanks for your interest and please read on!",
    "location": {
      "address": "Alegria Village",
      "postalCode": "",
      "city": "San Mateo",
      "countryCode": "CR",
      "region": "Alajuela",
      "countryName": "Costa Rica"
    },
    "profiles": [
      {
        "network": "Email",
        "url": "mailto:resume@douglaskent.com",
        "icon": "fa-regular fa-envelope"
      },
      {
        "network": "Website",
        "url": "https://www.douglaskent.com",
        "icon": "fa-solid fa-arrow-up-right-from-square"
      },
      {
        "network": "LinkedIn",
        "url": "https://www.linkedin.com/in/douglas-kent-760876a/",
        "icon": "fa-brands fa-linkedin"
      },
      {
        "network": "GitHub",
        "url": "https://github.com/dkent600",
        "icon": "fa-brands fa-github"
      }
    ]
  },
  "skillCategories": [
    "Website and Application Development",
    "Blockchain",
    "AI",
    "Software Languages",
    "Markup Languages",
    "Data Stores",
    "Module Bundling and Loading",
    "Software Development Platforms",
    "Test Frameworks",
    "Development Tools",
    "Website and Application Hosting",
    "Cryptography",
    "Localization/Globalization",
    "Charting & Graphing Frameworks",
    "Semantic Search Frameworks",
    "Cloud Services",
    "Operating Systems",
    "Development Processes"
  ],
  "work": [
    {
      "company": "Personal Project",
      "position": "dApp Designer and Developer",
      "remote": true,
      "website": "https://github.com/dkent600/batch-take-profit",
      "startDate": "2025-06",
      "summary": "Fully designed and created a sophisticated cryptocurrency portfolio management dApp. Is the frontend component of the Butterfly App Ecosystem, designed to execute scaled take-profit sales across multiple cryptocurrency exchanges.",
      "endDate": "2025-09",
      "highlights": [
        "In development, leveraged the AI coding assistant AI Copilot in VS Code",
        "Architecture: MVVM SPA app frontend: [ View ] → binds to → [ ViewModel ] → uses → [ Store ] → calls → [ Service ]",
        "Manages cryptocurrency assets across multiple exchanges",
        "Executes batch take-profit orders across multiple exchanges, with percentage-based or fixed-amount strategies",
        "Does real-time price monitoring and balance tracking, tracking order history and status"
      ],
      "skills": [
        "Defi",
        "AI Coding Assistent",
        "AI Copilot",
        "TypeScript",
        "Aurelia 2",
        "MVVM",
        "TailWindCss",
        "FluentUI Web Components",
        "Vite",
        "Axios",
        "GitHub"
      ]
    },
    {
      "company": "Personal Project",
      "position": "Multi-Exchange API Gateway Designer and Developer",
      "remote": true,
      "website": "https://github.com/dkent600/butterfly-services",
      "startDate": "2025-06",
      "summary": "Fully designed and created a Multi-Exchange REST API Gateway supporting secure cryptocurrency exchange operations, part of the Butterfly App Ecosystem. It  provides a Node.js service hosting REST API endpoints supporting cryptocurrency exchange operations with comprehensive safety mechanisms, testing, and production-ready integration.",
      "endDate": "2025-09",
      "highlights": [
        "In development, leveraged the AI coding assistant AI Copilot in VS Code",
        "Architecture: Layered Service-Oriented with Dependency Injection: [ API ] -> [ Services ] -> [ Infrastucture]",
        "Node.js with TypeScript",
        "Fastify server providing Swagger/OpenAPI documentation",
        "TSyringe for clean dependency injection architecture for Node.js",
        "Axios for exchange-API communications"
      ],
      "skills": [
        "Defi",
        "AI Coding Assistent",
        "AI Copilot",
        "Nodejs",
        "TypeScript",
        "Fastify",
        "TSyringe",
        "Vite",
        "Axios",
        "GitHub"
      ]
    },
    {
      "company": "Curve Labs",
      "position": "Blockchain Oracle Developer",
      "remote": true,
      "website": "https://www.curvelabs.eu/",
      "startDate": "2023-04",
      "summary": "Invited back on contract. Developed an automated \"Oracle\" service maintaining states of <a href=\"https://www.kolektivo.network/\" target=\"_blank\">Kolektivo</a> regenerative finance (Refi) smart contracts on the <a href=\"https://celo.org/\" target=\"_blank\">Celo</a> (EVM compatible) blockchain.",
      "endDate": "2023-05",
      "highlights": [
        "Worked on the <a href=\"https://celo.org/\" target=\"_blank\">Celo blockchain</a> with the tokens kG, kCur and cUSD and a Balancer WeightedPool (kCur <> cUSD) ported to Celo by Symmetric",
        "Leveraged smart contracts MentoReserve and the Balancer WeightedPool to maintain the value of the total supply of kCur in the MentoReserve contract equal to the value of the total supply of the kG token (by changing the total supply of kCur in the MentoReserve)",
        "Leveraged the Balancer WeightedPool to help maintain kCur price stability within an acceptable range in its role of backing up kG",
        "Leveraged <a href=\"https://defender.openzeppelin.com/\" target=\"_blank\">OpenZeppelin Defender</a> for managing private keys, encrypting secrets, sending transactions, hosting and invoking the service",
        "Reported the prices of cUSD, kCur and kG price to smart contract Oracles"
      ],
      "skills": [
        "Ethereum",
        "Defender",
        "Refi",
        "Defi",
        "TypeScript",
        "Javascript",
        "Solidity",
        "ethers.js",
        "Balancer Liquidity Pools",
        "Mento",
        "Celo",
        "GitHub"
      ]
    },
    {
      "company": "Curve Labs",
      "position": "Development Team Lead and Lead Developer",
      "remote": true,
      "website": "https://www.curvelabs.eu/",
      "startDate": "2020-08",
      "summary": "Led teams of 2-5 in the development of the frontends of multiple dApps running against the Ethereum blockchain focused on decentralized (Defi) and regenerative finance (Refi). Among others, led the development team for a Refi dApp designed to emerge a regenerative, decentralized economic system for the sovereign island nation of Curaçao.  Here are couple of sites, but note that some of their functionality has been discontinued: <a href='https://deals.prime.xyz' target='_blank'>Prime Deals</a> and <a href='https://launch.prime.xyz' target='_blank'>Prime Launch</a>.",
      "endDate": "2022-11",
      "highlights": [
        "Lead and sole coder of the dApp frontends of <a href=\"https://github.com/PrimeDAO/prime-pool-dapp\" target=\"_blank\">Prime Pools (no longer active)</a>, <a href=\"https://primelock.eth.link/\" target=\"_blank\">Prime Locking For Reputation</a> and the <a href=\"https://primedao.eth.link\" target=\"_blank\">original PrimeDAO Home Page (no longer active)</a>",
        "Coordinated a team of two and did the majority of coding of the dApp frontend of <a href=\"https://launch.prime.xyz/\"target=\"_blank\">Prime Launch</a>",
        "Coordinated a team of five and did much of the coding of the dApp frontend of <a href=\"https://deals.prime.xyz/\"target=\"_blank\">Prime Deals</a>",
        "Coordinated a team of two and participated in the coding of the dApp frontend of <a href=\"https://github.com/Kolektivo/kolektivo-dapp\" target=\"_blank\">Kolektivo (not currently active)</a>",
        "With the exception of the PrimeDAO Home Page, which uses React.js, the dApps were all implemented using the <a href=\"https://aurelia.io/\" target=\"_blank\">Aurelia</a> framework",
        "Leveraged many Ethereum smart contracts developed by CurveLabs, reviewing solidity for code quality, bugs and security, proposing accepted improvements and bug fixes",
        "Leveraged <a href=\"https://balancer.fi/\" target=\"_blank\">Balancer Liquidity Pools</a>, smart contracts that implement decentralized automated market makers",
        "Leveraged GnosisSafe API, for governance purposes",
        "Leveraged CoinGecko for token prices",
        "Interviewed applicants for developer and project lead positions",
        "As products, these applications are innovative and impressive. Read more about them at <a href=\"https://www.kolektivo.network/\" target=\"_blank\">Kolektivo</a> and <a href=\"https://www.prime.xyz\" target=\"_blank\">The Prime Suite</a> "
      ],
      "skills": [
